// <auto-generated />
using System;
using FredsBoats.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FredsBoats.Web.Migrations
{
    [DbContext(typeof(FredsBoatsContext))]
    [Migration("20260130074638_Addcomments")]
    partial class Addcomments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("FredsBoats.Web.Models.Boat", b =>
                {
                    b.Property<int>("BoatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("boatid");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fkcategoryid");

                    b.Property<int>("ColourId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fkcolourid");

                    b.Property<float>("DailyRate")
                        .HasColumnType("REAL")
                        .HasColumnName("daily_rate");

                    b.Property<float>("HourRate")
                        .HasColumnType("REAL")
                        .HasColumnName("hour_rate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("BoatId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ColourId");

                    b.ToTable("boat");
                });

            modelBuilder.Entity("FredsBoats.Web.Models.BoatColour", b =>
                {
                    b.Property<int>("ColourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("colourid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("ColourId");

                    b.ToTable("boat_colour");
                });

            modelBuilder.Entity("FredsBoats.Web.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("categoryid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("CategoryId");

                    b.ToTable("category");
                });

            modelBuilder.Entity("FredsBoats.Web.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BoatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("CommentId");

                    b.HasIndex("BoatId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("FredsBoats.Web.Models.CustReservation", b =>
                {
                    b.Property<int>("ResCustId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("res_cust_id");

                    b.Property<int>("BookingId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fkbookingid");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fkcustomerid");

                    b.HasKey("ResCustId");

                    b.HasIndex("BookingId");

                    b.HasIndex("CustomerId");

                    b.ToTable("cust_reservations");
                });

            modelBuilder.Entity("FredsBoats.Web.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("customerid");

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<bool>("Licence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("licence");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("TEXT")
                        .HasColumnName("surname");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("telephone");

                    b.HasKey("CustomerId");

                    b.ToTable("customer");
                });

            modelBuilder.Entity("FredsBoats.Web.Models.Reservation", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("bookingid");

                    b.Property<int>("BoatId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fkboatid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_date");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_date");

                    b.HasKey("BookingId");

                    b.HasIndex("BoatId");

                    b.ToTable("reservation");
                });

            modelBuilder.Entity("FredsBoats.Web.Models.Boat", b =>
                {
                    b.HasOne("FredsBoats.Web.Models.Category", "Category")
                        .WithMany("Boats")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FredsBoats.Web.Models.BoatColour", "BoatColour")
                        .WithMany("Boats")
                        .HasForeignKey("ColourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoatColour");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FredsBoats.Web.Models.Comment", b =>
                {
                    b.HasOne("FredsBoats.Web.Models.Boat", "Boat")
                        .WithMany("Comments")
                        .HasForeignKey("BoatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Boat");
                });

            modelBuilder.Entity("FredsBoats.Web.Models.CustReservation", b =>
                {
                    b.HasOne("FredsBoats.Web.Models.Reservation", "Reservation")
                        .WithMany("CustReservations")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FredsBoats.Web.Models.Customer", "Customer")
                        .WithMany("CustReservations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("FredsBoats.Web.Models.Reservation", b =>
                {
                    b.HasOne("FredsBoats.Web.Models.Boat", "Boat")
                        .WithMany("Reservations")
                        .HasForeignKey("BoatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Boat");
                });

            modelBuilder.Entity("FredsBoats.Web.Models.Boat", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("FredsBoats.Web.Models.BoatColour", b =>
                {
                    b.Navigation("Boats");
                });

            modelBuilder.Entity("FredsBoats.Web.Models.Category", b =>
                {
                    b.Navigation("Boats");
                });

            modelBuilder.Entity("FredsBoats.Web.Models.Customer", b =>
                {
                    b.Navigation("CustReservations");
                });

            modelBuilder.Entity("FredsBoats.Web.Models.Reservation", b =>
                {
                    b.Navigation("CustReservations");
                });
#pragma warning restore 612, 618
        }
    }
}
